### ISSUE TITLE
GitHub page build failure

### ISSUE THREAD

**Issue by mcasey24** [VIS-2129-F2020/mcasey-vis#3]
Hi Carole,
Alex mentioned I should create an issue regarding my page failure. Let me know if there is any info you need! Thanks!

**Comment by c-voulgaris** [comment]
Can you forward me the page build failure email you got from GitHub?

**Comment by c-voulgaris** [comment]
Nevermind, I found it.

I have administrative access to your repo, which allows me to edit your files and push them without you having to approve those changes.

Since I can't check to see if a page build failure is resolved without pushing the html file to GitHub, I want ahead and edited your code directly, so **before you commit to GitHub again, you'll need to pull my changes from RStudio** (click the little down arrow next to the up arrow you use when you push your files). Otherwise, you'll get an error next time you try to commit.

Here's what I changed:

On lines 34, 36, and 38, I deleted everything in the url after (and including) the question mark. You can see that change on the commit page here: https://github.com/VIS-2129-F2020/mcasey-vis/commit/77ec13dc098dbd9488ea437a5e0fb7ae5460175f

You can usually get away with this without breaking a link. As is happens, on line 40, that did break the link, so I just downloaded the KML file, added it to your repo, and read it directly from there. I like loading stuff directly from urls because it's more transparent - the reader can see exactly where you got your data from and have confidence that you didn't manipulate it before loading it. The next best thing is to include a link in the comments that shows where the data were downloaded from, so I added that. See the changes on the commit page here: https://github.com/VIS-2129-F2020/mcasey-vis/commit/7b06363fb8d5bee2239ebe6c8248f627c842b725

And now the page build works: Here's a link to your completed assignment: https://vis-2129-f2020.github.io/mcasey-vis/Creative3

It looks great, by the way.

**Comment by c-voulgaris** [comment]
I forgot to explain why those changes were necessary. 

There are couple of weird things that don't create a problem when you build a file, but they will stop GitHub from building a page for the public internet. I have no idea why. One of those things is if your Rmd file has a '{%' anywhere, but the closing bracket doesn't have a '%' before it. For some reason download links from municipal open data portals sometimes have this pattern in the download urls - and it's usually after a '?' in the middle of the url. Fortunately, you can usually just delete the part of the url after (and including the '?' and the url will still work. If it doesn't the next thing you can try is just downloading the file to your repo and and loading it directly from there.
